-- Create Products Table
create table products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    type text not null,
    region text,
    year integer,
    price numeric not null,
    description text,
    image text default '/images/products/douro-2018.png',
    featured boolean default false
);
-- Insert Mock Data
insert into products (
        name,
        type,
        region,
        year,
        price,
        description,
        featured,
        image
    )
values (
        'Reserva do Douro 2018',
        'Tinto',
        'Douro',
        2018,
        45.00,
        'Um vinho robusto com notas de frutas maduras, especiarias e carvalho.',
        true,
        '/images/products/douro-2018.png'
    ),
    (
        'Quinta do Alentejo 2019',
        'Branco',
        'Alentejo',
        2019,
        38.00,
        'Elegante e fresco, com aromas a citrinos e flores brancas.',
        true,
        '/images/products/alentejo-2019.png'
    ),
    (
        'Grande Reserva 2015',
        'Tinto',
        'Dão',
        2015,
        85.00,
        'Complexo e elegante, com taninos macios e longo final.',
        false,
        '/images/products/grande-reserva-2015.png'
    );
-- Enable Row Level Security (RLS)
alter table products enable row level security;
-- Create Policy: Allow Public Read Access
create policy "Public Read Access" on products for
select using (true);
-- Create Policy: Allow Public Insert/Update (TEMPORARY FOR ADMIN DEMO)
-- In production, this should be restricted to authenticated users only.
create policy "Public Write Access" on products for
insert with check (true);
create policy "Public Update Access" on products for
update using (true);
create policy "Public Delete Access" on products for delete using (true);